import type { EdgeType, NodeType, ScenarioTemplate, SimulationEdge, SimulationNode, SystemType } from '../types/simulation'

const node = (
  id: string,
  label: string,
  type: NodeType,
  x: number,
  y: number,
  overrides: Partial<SimulationNode['properties']> = {},
): SimulationNode => ({
  id,
  label,
  type,
  x,
  y,
  properties: {
    capacity: 100,
    demand: 55,
    throughput: 70,
    failureProbability: 0.04,
    recoveryTime: 3,
    cost: 30,
    priority: 5,
    resilience: 65,
    stock: 50,
    ...overrides,
  },
})

const edge = (
  id: string,
  label: string,
  source: string,
  target: string,
  type: EdgeType = 'flow',
  overrides: Partial<SimulationEdge['properties']> = {},
): SimulationEdge => ({
  id,
  label,
  source,
  target,
  type,
  properties: {
    flowCapacity: 80,
    travelTime: 1,
    cost: 10,
    reliability: 0.92,
    direction: 'directed',
    congestionSensitivity: 0.45,
    transferEfficiency: 0.88,
    dependencyStrength: 0.65,
    ...overrides,
  },
})

const scenario = (
  id: string,
  name: string,
  systemType: SystemType,
  description: string,
  goal: string,
  nodes: SimulationNode[],
  edges: SimulationEdge[],
  risks: string[],
  experiments: string[],
): ScenarioTemplate => ({
  id,
  name,
  systemType,
  description,
  goal,
  nodes,
  edges,
  visibleRisks: risks,
  suggestedExperiments: experiments,
  baselineMetrics: {
    totalThroughput: 420,
    bottleneckCount: risks.length,
    resilienceScore: 68,
    systemEfficiency: 72,
  },
})

export const scenarioTemplates: ScenarioTemplate[] = [
  scenario(
    'small-city-traffic-bottleneck',
    'Small City Traffic Bottleneck',
    'traffic',
    'A compact city corridor where commuters, commercial traffic, and a highway entrance compete for limited intersection capacity.',
    'Reduce queue buildup near the central intersection while preserving access to commercial demand.',
    [
      node('residential-west', 'West Homes', 'residential-zone', 90, 170, { demand: 75, capacity: 92, priority: 6 }),
      node('highway-ramp', 'Highway Ramp', 'highway-entrance', 120, 360, { demand: 90, capacity: 95, failureProbability: 0.05 }),
      node('central-junction', 'Central Junction', 'intersection', 360, 250, { capacity: 82, demand: 120, resilience: 44, priority: 9 }),
      node('market-district', 'Market District', 'commercial-zone', 610, 155, { demand: 100, capacity: 110, priority: 8 }),
      node('transit-spine', 'Transit Hub', 'transit-hub', 610, 360, { capacity: 125, demand: 65, resilience: 76 }),
      node('east-sink', 'Eastbound Exit', 'sink', 800, 260, { demand: 35, capacity: 160, throughput: 120 }),
    ],
    [
      edge('e1', 'Commuter Feed', 'residential-west', 'central-junction', 'flow', { flowCapacity: 72, congestionSensitivity: 0.7 }),
      edge('e2', 'Ramp Merge', 'highway-ramp', 'central-junction', 'flow', { flowCapacity: 65, congestionSensitivity: 0.75, dependencyStrength: 0.8 }),
      edge('e3', 'Retail Corridor', 'central-junction', 'market-district', 'flow', { flowCapacity: 58, reliability: 0.87 }),
      edge('e4', 'Transit Diversion', 'central-junction', 'transit-spine', 'flow', { flowCapacity: 52, reliability: 0.94 }),
      edge('e5', 'East Arterial', 'market-district', 'east-sink', 'flow', { flowCapacity: 92 }),
      edge('e6', 'Transit Express', 'transit-spine', 'east-sink', 'flow', { flowCapacity: 80, reliability: 0.96 }),
    ],
    ['Central junction demand exceeds capacity', 'Ramp merge has high congestion sensitivity', 'Transit diversion is underused'],
    ['Reduce central demand by 15%', 'Add alternate transit edge', 'Increase junction capacity'],
  ),
  scenario(
    'regional-supply-chain-disruption',
    'Regional Supply Chain Disruption',
    'supply-chain',
    'A supplier-to-retailer network with one fragile factory and insufficient warehouse buffer.',
    'Identify backup capacity that reduces unmet demand after supplier disruption.',
    [
      node('supplier-a', 'Primary Supplier', 'supplier', 80, 130, { capacity: 140, demand: 40, resilience: 72, stock: 90 }),
      node('supplier-b', 'Backup Supplier', 'supplier', 80, 360, { capacity: 58, demand: 20, resilience: 55, stock: 38 }),
      node('factory-main', 'Main Factory', 'factory', 320, 245, { capacity: 96, demand: 138, resilience: 42, priority: 9 }),
      node('warehouse', 'Regional Warehouse', 'warehouse', 540, 245, { capacity: 105, demand: 118, stock: 24, resilience: 52 }),
      node('distribution', 'Distribution Center', 'distribution-center', 710, 245, { capacity: 120, demand: 108, resilience: 63 }),
      node('retailer', 'Retail Demand', 'retailer', 870, 245, { capacity: 145, demand: 132, priority: 8 }),
    ],
    [
      edge('s1', 'Primary Inbound', 'supplier-a', 'factory-main', 'flow', { flowCapacity: 120, dependencyStrength: 0.9 }),
      edge('s2', 'Backup Inbound', 'supplier-b', 'factory-main', 'flow', { flowCapacity: 35, reliability: 0.82 }),
      edge('s3', 'Production Output', 'factory-main', 'warehouse', 'flow', { flowCapacity: 72, reliability: 0.78, congestionSensitivity: 0.8 }),
      edge('s4', 'Warehouse Transfer', 'warehouse', 'distribution', 'flow', { flowCapacity: 82, reliability: 0.86 }),
      edge('s5', 'Last Mile', 'distribution', 'retailer', 'flow', { flowCapacity: 92 }),
    ],
    ['Main factory is a single point of failure', 'Warehouse buffer is low', 'Backup supplier capacity is insufficient'],
    ['Simulate supplier failure', 'Increase warehouse stock', 'Add backup factory route'],
  ),
  scenario(
    'neighborhood-power-grid-failure',
    'Neighborhood Power Grid Failure',
    'power-grid',
    'A neighborhood grid with distributed generation, a central substation, and critical-facility load.',
    'Improve resilience when the central substation or transformer becomes unavailable.',
    [
      node('solar', 'Solar Field', 'generator', 95, 170, { capacity: 130, demand: 30, resilience: 78 }),
      node('battery', 'Battery Storage', 'storage-battery', 100, 365, { capacity: 75, stock: 80, demand: 25, resilience: 70 }),
      node('substation-core', 'Core Substation', 'substation', 345, 250, { capacity: 100, demand: 128, resilience: 38, priority: 10 }),
      node('transformer-north', 'North Transformer', 'transformer', 565, 150, { capacity: 74, demand: 88, resilience: 48 }),
      node('hospital', 'Clinic', 'critical-facility', 785, 130, { capacity: 84, demand: 92, priority: 10, resilience: 50 }),
      node('homes', 'Load Center', 'load-center', 765, 355, { capacity: 118, demand: 130, priority: 7 }),
    ],
    [
      edge('p1', 'Solar Feed', 'solar', 'substation-core', 'flow', { flowCapacity: 90, reliability: 0.92 }),
      edge('p2', 'Battery Support', 'battery', 'substation-core', 'flow', { flowCapacity: 55, reliability: 0.88 }),
      edge('p3', 'Critical Line', 'substation-core', 'transformer-north', 'dependency', { flowCapacity: 72, dependencyStrength: 0.95 }),
      edge('p4', 'Clinic Feed', 'transformer-north', 'hospital', 'dependency', { flowCapacity: 62, dependencyStrength: 0.9 }),
      edge('p5', 'Residential Feed', 'substation-core', 'homes', 'dependency', { flowCapacity: 78, reliability: 0.82 }),
    ],
    ['Core substation concentrates dependency', 'Critical facility has limited backup path', 'Residential demand is above load-center capacity'],
    ['Simulate power loss', 'Add storage capacity', 'Reduce clinic dependency on transformer'],
  ),
  scenario(
    'forest-ecosystem-balance',
    'Forest Ecosystem Balance',
    'ecosystem',
    'A simplified forest food web with producer growth, herbivore pressure, predator regulation, water constraints, and invasive species.',
    'Keep biodiversity and resource balance stable while reducing collapse risk.',
    [
      node('plants', 'Native Producers', 'producer', 130, 160, { capacity: 180, stock: 130, growthRate: 0.18, decayRate: 0.04, resilience: 70 }),
      node('water', 'Water Source', 'water-source', 110, 375, { capacity: 160, stock: 115, growthRate: 0.06, resilience: 62 }),
      node('deer', 'Herbivores', 'herbivore', 360, 250, { capacity: 135, stock: 92, growthRate: 0.12, decayRate: 0.08, demand: 85 }),
      node('wolves', 'Predators', 'predator', 610, 190, { capacity: 95, stock: 48, growthRate: 0.06, decayRate: 0.07, demand: 45 }),
      node('habitat', 'Habitat Core', 'habitat', 610, 365, { capacity: 130, stock: 74, resilience: 58 }),
      node('invasive', 'Invasive Species', 'invasive-species', 815, 280, { capacity: 120, stock: 84, growthRate: 0.2, decayRate: 0.02, resilience: 38 }),
    ],
    [
      edge('eco1', 'Grazing Pressure', 'plants', 'deer', 'resource', { flowCapacity: 78, transferEfficiency: 0.75 }),
      edge('eco2', 'Water Support', 'water', 'plants', 'resource', { flowCapacity: 65, reliability: 0.86 }),
      edge('eco3', 'Predation Balance', 'deer', 'wolves', 'predation', { flowCapacity: 44, dependencyStrength: 0.72 }),
      edge('eco4', 'Habitat Shelter', 'habitat', 'deer', 'resource', { flowCapacity: 52, reliability: 0.9 }),
      edge('eco5', 'Invasive Competition', 'invasive', 'plants', 'dependency', { flowCapacity: 70, dependencyStrength: 0.84 }),
    ],
    ['Invasive species pressure is growing', 'Habitat core has weak resilience', 'Water support constrains producer recovery'],
    ['Reduce invasive pressure', 'Restore habitat node', 'Increase water-source capacity'],
  ),
  scenario(
    'warehouse-throughput-optimization',
    'Warehouse Throughput Optimization',
    'factory',
    'A warehouse flow where input docks and machines outpace packing capacity, creating downstream queues.',
    'Increase completed output without simply adding capacity everywhere.',
    [
      node('input-a', 'Input Dock A', 'input-dock', 95, 210, { capacity: 130, demand: 55 }),
      node('input-b', 'Input Dock B', 'input-dock', 95, 360, { capacity: 100, demand: 50 }),
      node('sorter', 'Sorter Machine', 'machine', 315, 285, { capacity: 92, demand: 118, processingTime: 4, resilience: 46 }),
      node('buffer', 'Buffer Zone', 'buffer', 525, 285, { capacity: 75, stock: 20, demand: 92, resilience: 44 }),
      node('packing', 'Packing Station', 'packing-station', 715, 285, { capacity: 68, demand: 112, resilience: 40 }),
      node('output', 'Output Dock', 'output-dock', 880, 285, { capacity: 145, demand: 60 }),
    ],
    [
      edge('w1', 'Dock A Conveyor', 'input-a', 'sorter', 'flow', { flowCapacity: 82 }),
      edge('w2', 'Dock B Conveyor', 'input-b', 'sorter', 'flow', { flowCapacity: 74 }),
      edge('w3', 'Sorter Output', 'sorter', 'buffer', 'flow', { flowCapacity: 62, congestionSensitivity: 0.78 }),
      edge('w4', 'Buffer Pull', 'buffer', 'packing', 'flow', { flowCapacity: 58, reliability: 0.84 }),
      edge('w5', 'Ship Lane', 'packing', 'output', 'flow', { flowCapacity: 76 }),
    ],
    ['Packing station is the limiting station', 'Buffer capacity is too low', 'Sorter output route is congestion-sensitive'],
    ['Upgrade packing capacity', 'Add buffer stock', 'Rebalance dock flow'],
  ),
  scenario(
    'disease-spread-connected-communities',
    'Disease Spread in Connected Communities',
    'epidemic',
    'An educational population-dynamics model showing how contact hubs and mitigation nodes influence spread velocity.',
    'Explore containment strategies while clearly treating the model as educational only.',
    [
      node('community-a', 'Community A', 'population-group', 115, 190, { population: 900, infected: 22, recovered: 40, capacity: 900, contactRate: 0.18, infectionRate: 0.08, resilience: 58 }),
      node('community-b', 'Community B', 'population-group', 115, 380, { population: 720, infected: 10, recovered: 28, capacity: 720, contactRate: 0.14, infectionRate: 0.07, resilience: 62 }),
      node('hub', 'Transit Contact Hub', 'contact-hub', 360, 285, { capacity: 600, demand: 720, contactRate: 0.28, infectionRate: 0.11, resilience: 42 }),
      node('clinic', 'Healthcare Node', 'healthcare-node', 600, 180, { capacity: 160, demand: 175, resilience: 68, recoveryTime: 2 }),
      node('quarantine', 'Quarantine Zone', 'quarantine-zone', 600, 390, { capacity: 130, demand: 95, resilience: 75, contactRate: 0.04 }),
      node('community-c', 'Community C', 'population-group', 835, 285, { population: 600, infected: 6, recovered: 18, capacity: 600, contactRate: 0.13, infectionRate: 0.06 }),
    ],
    [
      edge('d1', 'Commute A', 'community-a', 'hub', 'mobility', { flowCapacity: 170, dependencyStrength: 0.74 }),
      edge('d2', 'Commute B', 'community-b', 'hub', 'mobility', { flowCapacity: 130, reliability: 0.88 }),
      edge('d3', 'Clinic Referral', 'hub', 'clinic', 'transmission', { flowCapacity: 95, transferEfficiency: 0.7 }),
      edge('d4', 'Mitigation Routing', 'hub', 'quarantine', 'transmission', { flowCapacity: 80, transferEfficiency: 0.78 }),
      edge('d5', 'Regional Mobility', 'hub', 'community-c', 'mobility', { flowCapacity: 110, dependencyStrength: 0.62 }),
    ],
    ['Contact hub is overloaded', 'Healthcare demand exceeds capacity', 'Regional mobility can accelerate spread'],
    ['Increase mitigation capacity', 'Reduce contact hub traffic', 'Simulate population spike'],
  ),
  scenario(
    'emergency-shelter-resource-network',
    'Emergency Shelter Resource Network',
    'resilience',
    'A disaster-response resource network balancing shelters, supplies, power, water, and transport reliability.',
    'Find weak recovery zones before a disruption creates a resource cascade.',
    [
      node('supply-depot', 'Supply Depot', 'source', 110, 245, { capacity: 145, stock: 110, resilience: 66 }),
      node('water', 'Water Station', 'storage', 295, 140, { capacity: 86, stock: 54, demand: 92, resilience: 46 }),
      node('power', 'Mobile Power', 'generator', 300, 365, { capacity: 78, demand: 90, resilience: 50 }),
      node('shelter-a', 'Shelter A', 'consumer', 535, 190, { capacity: 120, demand: 135, priority: 9 }),
      node('shelter-b', 'Shelter B', 'consumer', 535, 360, { capacity: 95, demand: 104, priority: 8 }),
      node('hospital-aid', 'Medical Aid', 'critical-facility', 775, 270, { capacity: 72, demand: 88, priority: 10, resilience: 47 }),
    ],
    [
      edge('r1', 'Food Transfer', 'supply-depot', 'shelter-a', 'dependency', { flowCapacity: 72, reliability: 0.86 }),
      edge('r2', 'Food Alternate', 'supply-depot', 'shelter-b', 'dependency', { flowCapacity: 58, reliability: 0.8 }),
      edge('r3', 'Water Route A', 'water', 'shelter-a', 'dependency', { flowCapacity: 44, dependencyStrength: 0.88 }),
      edge('r4', 'Power Route B', 'power', 'shelter-b', 'dependency', { flowCapacity: 46, dependencyStrength: 0.82 }),
      edge('r5', 'Medical Priority', 'shelter-a', 'hospital-aid', 'dependency', { flowCapacity: 38, reliability: 0.76 }),
      edge('r6', 'Medical Alternate', 'shelter-b', 'hospital-aid', 'dependency', { flowCapacity: 34, reliability: 0.72 }),
    ],
    ['Medical aid depends on weak shelter routes', 'Water station is under capacity', 'Power route has limited redundancy'],
    ['Simulate resource shortage', 'Invest in recovery at water station', 'Add medical alternate route'],
  ),
  scenario(
    'custom-blank-network',
    'Custom Blank Network',
    'custom',
    'A small editable starter graph for custom node-network experiments.',
    'Sketch a system, run a baseline, and compare changes with snapshots.',
    [
      node('source-1', 'Source', 'source', 140, 260, { capacity: 120, demand: 35, stock: 100 }),
      node('hub-1', 'Hub', 'hub', 410, 260, { capacity: 92, demand: 82, resilience: 60 }),
      node('sink-1', 'Sink', 'sink', 700, 260, { capacity: 140, demand: 95 }),
    ],
    [
      edge('c1', 'Primary Flow', 'source-1', 'hub-1', 'flow', { flowCapacity: 80 }),
      edge('c2', 'Delivery Flow', 'hub-1', 'sink-1', 'flow', { flowCapacity: 76 }),
    ],
    ['Hub is the first likely bottleneck'],
    ['Add redundant route', 'Increase sink demand', 'Reduce edge capacity'],
  ),
]

export const getScenarioById = (id: string): ScenarioTemplate =>
  scenarioTemplates.find((scenarioItem) => scenarioItem.id === id) ?? scenarioTemplates[0]

export const cloneScenario = (scenarioItem: ScenarioTemplate): ScenarioTemplate =>
  JSON.parse(JSON.stringify(scenarioItem)) as ScenarioTemplate
